# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20140509051218) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "cards", force: true do |t|
  t.string "name"
  t.text "description"
  t.text "photo"
  t.boolean "male"
  t.boolean "glasses"
  t.boolean "hat"
  t.boolean "facial_hair"
  t.boolean "mustache"
  t.boolean "jewelry"
  t.boolean "earrings"
  t.boolean "facial_piercing"
  t.string "hair_color"
  t.string "eye_color"
  end

  # create_table "cards", force: true do |t|
  #   t.string   "name"
  #   t.text     "description"
  #   t.text     "photo"
  #   t.boolean  "male"
  #   t.boolean  "glasses"
  #   t.boolean  "hat"
  #   t.boolean  "facial_hair"
  #   t.boolean  "beard"
  #   t.boolean  "mustache"
  #   t.boolean  "jewelry"
  #   t.boolean  "earrings"
  #   t.boolean  "necklass"
  #   t.boolean  "facial_piercing"
  #   t.boolean  "scarf"
  #   t.boolean  "red_head"
  #   t.boolean  "blonde"
  #   t.boolean  "black_hair"
  #   t.boolean  "brunette"
  #   t.boolean  "bookbag"
  #   t.boolean  "purse"
  #   t.boolean  "holding_phone"
  #   t.boolean  "headphones"
  #   t.boolean  "hair_clip"
  #   t.boolean  "hair_tie"
  #   t.boolean  "hair_band"
  #   t.boolean  "stubble"
  #   t.boolean  "duck_face"
  #   t.boolean  "funny_face"
  #   t.boolean  "hand_signal"
  #   t.boolean  "peace_sign"
  #   t.boolean  "rocker_sign"
  #   t.boolean  "shocker"
  #   t.boolean  "hands_visible"
  #   t.boolean  "painted_nails"
  #   t.boolean  "ring"
  #   t.boolean  "kiss_face"
  #   t.boolean  "smile"
  #   t.boolean  "sunglasses"
  #   t.boolean  "towel"
  #   t.boolean  "tank_top"
  #   t.boolean  "t_shirt"
  #   t.boolean  "ear_buds"
  #   t.boolean  "monocle"
  #   t.boolean  "cowboy_hat"
  #   t.boolean  "baseball_cap"
  #   t.boolean  "smoking"
  #   t.boolean  "cigarette"
  #   t.boolean  "blunt"
  #   t.boolean  "pipe"
  #   t.boolean  "cigar"
  #   t.boolean  "drinking"
  #   t.boolean  "mask"
  #   t.boolean  "helmet"
  #   t.boolean  "camera_visible"
  #   t.boolean  "self_shot"
  #   t.boolean  "brown_eyed"
  #   t.boolean  "blue_eyed"
  #   t.boolean  "green_eyed"
  #   t.boolean  "black_eyed"
  #   t.boolean  "hazel_eyed"
  #   t.boolean  "red_eyed"
  #   t.boolean  "bracelet"
  #   t.boolean  "spiked_hair"
  #   t.boolean  "straight_hair"
  #   t.boolean  "mullet"
  #   t.boolean  "curly_hair"
  #   t.boolean  "wavey_hair"
  #   t.boolean  "long_hair"
  #   t.boolean  "short_hair"
  #   t.boolean  "female"
  #   t.boolean  "bowl_cut"
  #   t.boolean  "crew_cut"
  #   t.boolean  "pixie_cut"
  #   t.boolean  "perm"
  #   t.boolean  "wig"
  #   t.boolean  "green_hair"
  #   t.boolean  "pink_hair"
  #   t.boolean  "purple_hair"
  #   t.boolean  "blue_hair"
  #   t.boolean  "red_lipstick"
  #   t.boolean  "lipstick"
  #   t.boolean  "black_lipstick"
  #   t.boolean  "purple_lipstick"
  #   t.boolean  "eye_piercing"
  #   t.boolean  "lip_piercing"
  #   t.boolean  "nose_piercing"
  #   t.boolean  "tie"
  #   t.boolean  "neck_tie"
  #   t.boolean  "bow_tie"
  #   t.boolean  "tongue_out"
  #   t.boolean  "eyes_closed"
  #   t.boolean  "handle_bar_mustache"
  #   t.boolean  "mutton_chops"
  #   t.boolean  "sideburns"
  #   t.boolean  "costume"
  #   t.boolean  "indoors"
  #   t.boolean  "outdoors"
  #   t.boolean  "eye_liner"
  #   t.boolean  "mascara"
  #   t.boolean  "tiara"
  #   t.boolean  "hood"
  #   t.boolean  "hoodie"
  #   t.boolean  "jacket"
  #   t.boolean  "dress"
  #   t.boolean  "shirtless"
  #   t.boolean  "slicked_back_hair"
  #   t.boolean  "bangs"
  #   t.boolean  "teeth_showing"
  #   t.boolean  "pearl_necklace"
  #   t.boolean  "pearl_earring"
  #   t.boolean  "fur"
  #   t.boolean  "hoop_earring"
  #   t.boolean  "chewing_gum"
  #   t.boolean  "eating"
  #   t.boolean  "goatee"
  #   t.boolean  "soul_patch"
  #   t.boolean  "milk_mustache"
  #   t.boolean  "beanie"
  #   t.boolean  "ski_cap"
  #   t.boolean  "braided_hair"
  #   t.boolean  "straw_hat"
  #   t.boolean  "holding_object"
  #   t.boolean  "posing_with_animal"
  #   t.boolean  "people_in_background"
  #   t.boolean  "in_car"
  #   t.boolean  "on_beach"
  #   t.boolean  "in_bathroom"
  #   t.boolean  "mirror_pic"
  #   t.boolean  "face_paint"
  #   t.boolean  "backwards_hat"
  #   t.boolean  "dog_tags"
  #   t.boolean  "trucker_hat"
  #   t.boolean  "camo"
  #   t.boolean  "stripes"
  #   t.boolean  "plaid"
  #   t.boolean  "red"
  #   t.boolean  "blue"
  #   t.boolean  "green"
  #   t.boolean  "yellow"
  #   t.boolean  "white"
  #   t.boolean  "gray"
  #   t.boolean  "orange"
  #   t.boolean  "purple"
  #   t.boolean  "cyan"
  #   t.boolean  "magenta"
  #   t.boolean  "pink"
  #   t.boolean  "with_cat"
  #   t.boolean  "with_dog"
  #   t.datetime "created_at"
  #   t.datetime "updated_at"
  # end

end
